"""empty message

Revision ID: 620d929857f2
Revises: de451cf40258
Create Date: 2023-09-17 11:42:07.799987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '620d929857f2'
down_revision = 'de451cf40258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('security_permissions',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('create_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('last_seen',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('last_seen',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('create_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('security_permissions',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###
