"""empty message

Revision ID: 75edb0ae951c
Revises: badc54215972
Create Date: 2023-09-01 12:09:56.505413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75edb0ae951c'
down_revision = 'badc54215972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('security_permissions', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('security_permissions')

    # ### end Alembic commands ###
