"""empty message

Revision ID: edbf5b06a085
Revises: f26acd4b3f63
Create Date: 2023-09-09 13:55:59.333647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edbf5b06a085'
down_revision = 'f26acd4b3f63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telephone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phoneNumber', sa.Integer(), nullable=True))
        batch_op.drop_column('phoneNum')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telephone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phoneNum', sa.INTEGER(), nullable=True))
        batch_op.drop_column('phoneNumber')

    # ### end Alembic commands ###
