"""empty message

Revision ID: f26acd4b3f63
Revises: 839d4a0f4f26
Create Date: 2023-09-09 13:43:49.132015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f26acd4b3f63'
down_revision = '839d4a0f4f26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telephone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phoneNum', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telephone')
    # ### end Alembic commands ###
